!ifndef DEFINITIONS
	!define DEFINITIONS
	
	
	!define PROGRAM_NAME "Scrupdate"
	!define PROGRAM_VERSION "1.0.1.0"
	!define PROGRAM_PUBLISHER "Matan Brightbert"
	!define PROGRAM_COPYRIGHT "Copyright © 2021-2023 ${PROGRAM_PUBLISHER}"
	
	!define INSTALLER_CAPTION "${PROGRAM_NAME} - Installer"
	!define UNINSTALLER_CAPTION "${PROGRAM_NAME} - Uninstaller"
	!define TEMPORARY_INSTALLER_EXTRACTION_LOCATION "$TEMP\${PROGRAM_NAME}"
	!define TEMPORARY_INSTALLER_FILES_EXTRACTION_LOCATION "${TEMPORARY_INSTALLER_EXTRACTION_LOCATION}\files"
	!define INSTALLER_NAME "${PROGRAM_NAME}-${PROGRAM_VERSION}-installer.exe"
	!define USER_AUTO_INSTALLER_NAME "${PROGRAM_NAME}-${PROGRAM_VERSION}-user_auto_installer.exe"
	!define SYSTEM_AUTO_INSTALLER_NAME "${PROGRAM_NAME}-${PROGRAM_VERSION}-system_auto_installer.exe"
	!define UNINSTALLER_NAME "uninstaller.exe"
	!define DEFAULT_USER_INSTALL_LOCATION "$LOCALAPPDATA\${PROGRAM_NAME}"
	!define DEFAULT_SYSTEM_32BIT_INSTALL_LOCATION "$PROGRAMFILES\${PROGRAM_NAME}"
	!define DEFAULT_SYSTEM_64BIT_INSTALL_LOCATION "$PROGRAMFILES64\${PROGRAM_NAME}"
	!define INSTALLER_ARGUMENT__INSTALL_LOCATION "/install-location"
	!define INSTALLER_ARGUMENT__CREATE_DESKTOP_SHORTCUT "/create-desktop-shortcut"
	!define INSTALLER_ARGUMENT__CREATE_START_MENU_SHORTCUT "/create-start-menu-shortcut"
	!define PROGRAM_ARGUMENT__RESET_ALL_AND_CLOSE "/reset-all-and-close"
	!define PROGRAM_ARGUMENT__RESET_SCHEDULED_TASK_AND_CLOSE "/reset-scheduled-task-and-close"
	!define PROGRAM_ARGUMENT__UPDATE_SCHEDULED_TASK_AND_CLOSE "/update-scheduled-task-and-close"
!endif
